### Create Access Token
POST http://localhost:8080/oauth/access_token
Content-Type: application/json

{
  "access_token": "abc123",
  "username": "komdosh@yandex.ru",
  "password": "0",
  "grant_type": "password"
}

### Get Access Token
GET http://localhost:8080/oauth/access_token/abc123